language: java
jdk:
  - openjdk11
services:
  - docker  
  
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull openjdk:11-jre-slim-sid
  - chmod +x mvnw
 
script:
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent install
  - ./mvnw deploy jib:build -P deploy-heroku,deploy-docker
  
after_success:
  - bash <(curl -s https://codecov.io/bash)